CFLAGS = -std=gnu11 -Wall -Werror -Wextra -O2 -g
FILESTOMAKE = task1_server task1_client task2 task3_server task3_client

.PHONY: all
all: $(FILESTOMAKE)

.PHONY: clean
clean:
	rm -rf $(FILESTOMAKE) *.dSYM